### ISSUE TITLE
Create auth0 server auth example

### ISSUE THREAD

**Issue by ianjennings** [pubnub/chat-engine#132]
Auth0 is an oauth provider that provides login for google, github, etc... 

It can act as a generic oauth provider for many services. A server.js (or pubnub functions) example using auth0 would kill many birds with one stone and provides a generic api example.

**Comment by gtulga** [comment]
Hi @ianjennings ,

I'm interesting auth0 + pubnub implementation. Have you progress on this? Please share.

Thanks
