### ISSUE TITLE
Webpack fails to minify

### ISSUE THREAD

**Issue by kraynel** [pubnub/chat-engine#153]
Hi!

I have a problem minifying your plugins using the default webpack configuration from Create React App. It fails to build and give me a link to this section of the documentation: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

It seems to be related: I cannot create a production build for the example in https://github.com/pubnub/chat-engine-examples/tree/master/react: `yarn run build` fails.

Any hints to get me started?

**Comment by kraynel** [comment]
Using babel to convert `src/index.js` to an ES5 package and exposing this ES5 module in `package.json` worked for me: https://github.com/kraynel/chat-engine/commit/cfdd5b1bd2e46b9ea74d68541f1babc9fd1e1766

**Comment by AdamTyler** [comment]
Maybe you should PR your changes as this is still a problem with this repo.
