### ISSUE TITLE
Invalidating 'Me' or ChatEngine.disconnect()

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#257]
@ianjennings 

Hi!,

I am trying to invalidate the current Me object on my login/logout so I can switch between anonymous and logged-in UUIDs/sessions. Is there a way to do this? I can't recreate the ChatEngineCore instance because I am using a singleton factory instance in Angular.

Thanks!

Logan

**Comment by ianjennings** [comment]
Hey @logan-jobzmall, this is something we're working on now. You can follow along here: https://github.com/pubnub/chat-engine/tree/refresh-auth. The API is subject to change. I'll keep this issue open and update it as there is progress.

**Comment by logan-jobzmall** [comment]
Awesome! Thanks. I am watching the project so I will be looking at that branch closely as it is very pertinent to our workflow. Thank you so much for the support.

**Comment by ianjennings** [comment]
Hey @logan-jobzmall, #289 was merged into master which includes these patterns. See the integrations tests:
https://github.com/pubnub/chat-engine/blob/master/test/integration/main.test.js#L568
