### ISSUE TITLE
Wrong device count in user admin Panel .

### ISSUE THREAD

**Issue by deepak1725** [pubnub/chat-engine#262]
Pubnub Admin Panel giving wrong device count.
My App is in developement, and I even dont have 64 devices in total. 
i guess every Login or page refresh , pubnub counts as unique device..! 
Thats is certainely not desirable. 
[Ref. ScreenShot](https://screenshots.firefox.com/EvW94ZGyQkGQgteh/admin.pubnub.com)

**Comment by ianjennings** [comment]
When you call ```ChatEngine.connect(uuid)```, make sure ```uuid``` is consistent for each user. Otherwise PubNub will generate a unique UUID which will count as a unique device.

https://support.pubnub.com/support/solutions/articles/14000043671-how-do-i-set-the-uuid-

**Comment by deepak1725** [comment]
This was not so in case of SDK's.. :(
