### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by deepak1725** [pubnub/chat-engine#263]
i am on node ChatEngine version.

Sys Info:
ChatEngine lib. source: npm
npm: 5.6
Languge: Typescript (Angular4)
Build System : Webpack 3.5

Code: 
```
callStack = () => {
        this.initialize();
        this.lobby();
        this.subscribe();
        
    }
    
    initialize = () => {
        this.ChatEngine = ChatEngineCore.create({
            publishKey: 'pub-c-key',
            subscribeKey: 'sub-c-key'
        });
    }

    lobby = () => {
        this.ChatEngine.connect(String(new Date().getTime()), {
            nickName: 'rajmohan'
        });

        this.ChatEngine.on('$.ready', (data) => {
            let me = data.me;

            console.log("Ready to Go");
            
        });
        
    }

    subscribe = (channel="") => {
        let myChat = new (this.ChatEngine).Chat('chatengine-demo-room');

        myChat.on('message', (message) => {
            console.log("Message Received");
        });
    }

    publish = (message="") => {
     
            // create a new ChatEngine Chat
            let myChat = new (this.ChatEngine).Chat(this.room);

           
            myChat.emit('message', {
                text: message
            });

            console.log("Message Sent");
            
    }
```
Issue is: When i publish message , it gives me error: 
```
ERROR Error: Uncaught (in promise): TypeError: Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at parseValue (buildURL.js:54)
    at Object.forEach (utils.js:218)
    at resolvePromise (zone.js:770)
    ...
```
i guess Angular's Dependency Injection is not satisfying with our code.

Code reference : 
https://github.com/deepak1725/django-angular4/blob/dk-chat-engine/users/static/ngApp/angular2/src/app/_services/newchat.service.ts

**Comment by ianjennings** [comment]
Hey @deepak1725, we are aware of this issue. ChatEngine uses circular reference in many places and I can understand that causing problems with Angular.

We will either remove circular references or find out what is causing the problem within Angular. 

Currently I believe it to be a problem with ChatEngine.me.

I don't have a solution at this time but will look into it tonight.

**Comment by ianjennings** [comment]
It looks like you create the same Chat twice. Can you try to only create it once? 

```js
let myChat = new (this.ChatEngine).Chat('chatengine-demo-room');

room: string = 'chatengine-demo-room';
let myChat = new (this.ChatEngine).Chat(this.room);
```

I think creating the same Chat twice is leading to Angular circ reference. 

Ian

**Comment by deepak1725** [comment]
@ianjennings 
Yeah.. that really solved circular reference in this case. 

The new message added is quite sufficient of its own:
```
{error: "You must call ChatEngine.connect() and wait for the $.ready event before creating new Chats."}
```
thank you!
