### ISSUE TITLE
Message event - sender.state is empty

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#265]
Hey @ianjennings,

Thanks for all the help prior. Everything seems to be working well now that we figured out the channel name issues. I have do have an issue thought. The sender.state on the message event payload is empty, although it isn't empty everywhere else. Let me know if you need more information.

Logan

**Comment by ianjennings** [comment]
Interesting, do you have another code sample? Every ```User``` object should only exist once, so the state should be populated assuming it really is the same user.

**Comment by ianjennings** [comment]
Also what is the value of ```user._stateFetched``` at the time you're fetching state?

**Comment by logan-jobzmall** [comment]
Oops sorry took a screenshot of the wrong user on the second screenshot one sec.

**Comment by logan-jobzmall** [comment]
ANNNDDD while I was getting that output for you, I fixed it. Sorry for wasting more of your time. Lord. I am just making sure now that I use ChatSelf.profile.update() when we login and it seems to be consistent now.
