### ISSUE TITLE
State being sent over URL vs JSON payload

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#267]
Hey @ianjennings - Sorry to bug you one more time. I noticed that the state object was being sent over URL rather than in a JSON body payload, and because we have a lot of metadata around a user, we are sending a rather large payload and it causing an error:

<img width="1206" alt="screen shot 2017-12-18 at 6 43 46 pm" src="https://user-images.githubusercontent.com/31047862/34138360-efa2a0e0-e423-11e7-874a-bdd90e32ee96.png">

Thought I would bring that to your attention. If we need to cut down on our object size, I can definitely arrange that. Let me know. Thanks!

**Comment by ianjennings** [comment]
How big is the state? This is a hard PubNub limit and not something we can change in ChatEngine right now.

**Comment by logan-jobzmall** [comment]
Ahh okay. Well then I can cherrypick some important properties on the user object and get the rest on a lazy-loaded call when we open the chats then. No issue! Thanks!
