### ISSUE TITLE
Get a list of previous invites that happened while offline

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#269]
Hey @ianjennings,

Is it possible to be able to get a list of chats that a user was a invited to while they were offline at runtime so we can decide whether or not to accept them or not when they log back in?

Logan

**Comment by ianjennings** [comment]
Try something like this:

```
me.direct.search({
event: '$.invite'
}).on('$.invite', (payload) => {
    //...
});
```

**Comment by logan-jobzmall** [comment]
Hmm. I had that already, which but I just found this which I guess would make sense. Invites aren't being made due to this error (on `chat.invite()`):

<img width="1206" alt="screen shot 2017-12-19 at 11 23 43 am" src="https://user-images.githubusercontent.com/31047862/34174815-1dba71f2-e4af-11e7-8e98-67a4aae437d0.png">

Are there any ways to get better error reporting on this?

**Comment by ianjennings** [comment]
Are you supplying a full```User``` object into ```chat.invite()```? 

https://www.pubnub.com/docs/chat-engine/private-chat

**Comment by logan-jobzmall** [comment]
Ahh I am not. I was trying to invite based on UUID `chat.invite({uuid: user.id})` because I don't have access to that user's user object at the time of inviting (of course unless they are online I could get it from the global channel, but if they aren't does the global channel hold all users even if they are offline?). If there is a way of retrieving a user's ChatEngine object without fail, I could do that. I assume you have more insight. Thanks. I apologize for the hand-holding.

**Comment by ianjennings** [comment]
You can create the user on the fly:

```
chat.invite(new User('uuid'););
```

**Comment by logan-jobzmall** [comment]
Kick ass! Thanks!
