### ISSUE TITLE
Ensure that me.session does not include chats that have been left

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#271]
The issue is that when the page is refreshed (no matter how long I wait for the event), the list is still populated with chats that have been left.

Original Message:

Hey @ianjennings,

The title says it all, quick question. Is Me.chatEngine.chats population scoped to the current Me user? Should chats in there come up if that user is was not invited or subscribed to it? 

Thanks,

Logan

**Comment by ianjennings** [comment]
No, ```me.chatEngine``` is the same as the global ```chatEngine```.

```me.session.chats``` contains all ```chats``` ```me``` has joined (synced by uuid across devices).

**Comment by ianjennings** [comment]
https://www.pubnub.com/docs/chat-engine/reference/me#session

**Comment by logan-jobzmall** [comment]
@ianjennings Thanks for that! - When you leave() the chat, will that remove a record in that map? It doesn't seem like it on my end. Is there a way to remove the records from that map?

**Comment by ianjennings** [comment]
Oh shoot, you found another bug. You can find out when you leave with ```$.session.chat.leave``` event, but the map does not reflect that properly.

**Comment by ianjennings** [comment]
You're welcome to submit a pull request at any time.

Looking at the code now, it seems like it waits for the leave event from the server, which can take a minute. Can you try subscribing to that event, then checking the map?

**Comment by logan-jobzmall** [comment]
@ianjennings - The issue is that when the page is refreshed (no matter how long I wait for the event), the list is still populated with chats that have been left.

**Comment by logan-jobzmall** [comment]
@ianjennings - I hope you had a merry christmas. Just wanted to check up on this.

**Comment by ianjennings** [comment]
Currently working on #257. Leaving *should* work, but I'll write a test for this.

**Comment by logan-jobzmall** [comment]
Okay thank you! Still seeing the same results at the moment.

**Comment by ianjennings** [comment]
Hey I'm closing this as it's very similar to #266.

**Comment by ianjennings** [comment]
Hey @logan-jobzmall, working on this on #297

**Comment by logan-jobzmall** [comment]
@ianjennings thank you so much! I saw that disconnect() etc was implemented. What is your guys' release schedule (so I don't have to rely on master)?

**Comment by madisonsmith** [comment]
@logan-jobzmall we don't have a set schedule currently as we are going to lean more towards feature releases rather the time releases. With that said we hope to have a release out in the next 3-4 weeks with a lot of new goodies! 🎈 Thanks for all your feedback and bug finding!

**Comment by ianjennings** [comment]
Hey @logan-jobzmall, this *should* be fixed in ```0.9.5``` assuming you manually call ```chat.leave()```. Can you test it out and re-open or refile this bug if it still doesn't work as you expect?
