### ISSUE TITLE
Publish es5 to npm

### ISSUE THREAD

**Issue by AdamTyler** [pubnub/chat-engine#275]
When trying to build chat-engine inside a create-react-app environment, this issue comes up: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I forked v0.8.4 and transpiled to es5 via webpack [here](https://github.com/AdamTyler/chat-engine/commit/1e538d2330e14c46444d7ce1fb3c81487da64afe). I'm not sure this is the wanted solution but it worked for my case

**Comment by anonrig** [comment]
Can you try adding a babel-polyfill?

```javascript
npm i --save babel-polyfill
```

Add the following line to the first line of the index.ios.js or index.js

```javascript
import 'babel-polyfill';
```

**Comment by iMerica** [comment]
I replaced: `"chat-engine": "^0.8.4",` with`"chat-engine": "github:AdamTyler/chat-engine#1e538d2330e14c46444d7ce1fb3c81487da64afe",` in my `package.json` to fix this issue

Thanks @AdamTyler! 

Create React Is a pretty popular toolkit so this can potentially affect a lot of React users.

**Comment by AdamTyler** [comment]
This was addressed in PR #340. Closing
