### ISSUE TITLE
sender state empty for disconnected users in history

### ISSUE THREAD

**Issue by AdamTyler** [pubnub/chat-engine#276]
When performing a search to get old messages in a chat room, if a message is found that has a user that has been disconnected for a while, the sender state is an undefined object.

Example (react): 
```
    this.chatRoom.search({
      event: 'message',
      limit: OLD_MSGS_TO_SHOW
    }).on('message', msg => {
      this.setState({messages: [msg, ...this.state.messages]})
    })
```

resulting array:
![image](https://user-images.githubusercontent.com/2525253/34835969-1591742a-f6bc-11e7-8279-a3ee02cbc637.png)

**Comment by ianjennings** [comment]
Hey @AdamTyler. We do attempt to store state for offline users specifically for this use case. This may be malfunctioning.

Also, the code example you shared does not appear optimal. For every message returned by ```search``` it attempts to store every message in the user object. This will call ```pubnub.setState``` 50 times.

For example, if my user is ```ian```, then ```ian.state.messages``` will include all the messages returned by search. In addition, every other user will be notified of the state update 50 times, and the messages will be publically available to all other users.

```js
this.chatRoom.search({
      event: 'message',
      limit: OLD_MSGS_TO_SHOW
    }).on('message', msg => {
      this.setState({messages: [msg, ...this.state.messages]})
    })
```

**Comment by AdamTyler** [comment]
I'm confused by your message. In the above code example, I'm trying to get a history of old messages in a chat room.
Running `this.chatRoom.search` should only search for `message` events on the chat room correct? So how would I be getting messages on the user state? 

this `setState` is being called on my react component. I should only be called up to the `OLD_MSGS_TO_SHOW` variable.

**Comment by madisonsmith** [comment]
@AdamTyler we'll take a look at this in 0.9.5. Have you had a chance to take a stab at optimizing any? We should be able to provide a good example. This should help reduce a lot of networking and potential extra requests as @ianjennings suggest. I think we can make the history of messages in your app a load faster. Happy to brainstorm a few ways history can work if you want to explore.

**Comment by AdamTyler** [comment]
I haven't looked at optimizing that any. It follows the docs for search as far as I can tell.  The `setState` that I'm calling in that code above is called on the react component and not on pubnub so I don't think that has the affect that @ianjennings had suggested.
I'm happy to try any suggestions you have to optimize the search.

**Comment by madisonsmith** [comment]
Sounds good. We've pulled this work into the sprint this morning and will look at addressing the main issue and possibly optimizations from there.

**Comment by ManuelFernando** [comment]
@AdamTyler in the v0.9.5 is resolved your issue, btw I don’t know if you are using this event **$.search.finish** you can use this to invoke setState and reduce the number of times which react is going to render according to the change of state, pls let know us if this works for you

**Comment by AdamTyler** [comment]
@ManuelFernando cool. Will try incorporating that event into the code soon
