### ISSUE TITLE
timetoken is not included in message history

### ISSUE THREAD

**Issue by jalexander** [pubnub/chat-engine#279]
When doing a search on message history, timetokens are not included in the response

`let searchy = chat.search({
    event: 'message',
    limit: 50,
   includeTimetoken: true
});`

I see that this is set to default at https://github.com/pubnub/chat-engine/blob/18da2bd51a22a602b775dc32f6c2fb4f6a7369c2/src/components/search.js#L41

Is this the correct way to get timestamps on messages from history?

**Comment by ianjennings** [comment]
Hey @jalexander, thanks for the report. Unfortunately the SDK is not forwarding the timetoken correctly. This will need a code change.

**Comment by jzhw0130** [comment]
@ianjennings 

Any update?  Thx

**Comment by ianjennings** [comment]
Hey @jzhw0130! We've released ChatEngine version ```0.9.5``` which includes this fix! It's on NPM.
