### ISSUE TITLE
Can able to subscribe single chat channel multiple times.

### ISSUE THREAD

**Issue by deepak1725** [pubnub/chat-engine#307]
Single Chat Channel can be subscribed multiple times and hence on message publish, same message with **multiple copies** renders at same time.

**Comment by ianjennings** [comment]
Hey @deepak1725, can you please share some code? Event emitter patterns typically allow multiple subscriptions. You may look into using the ```off``` function to remove listeners.

**Comment by deepak1725** [comment]
Sure !! this is what i mean...
this is minimalist code...
 
(this is not my actual code, but some how scenario created to make you guys better understand, what i mean)
```
 let myAllChats = ['ChannelA', 'ChannelB', 'ChannelC']
  
  //Chat Create
  createChat = () => {
     for ( let chats in this.myAllChats){  
            let chat = new ChatEngine.Chat(chat);  //This will generate an Event 
       } 
    }

    //Event Listner
      this.ChatEngine.on('$.created.chat', (data, chat) => {
                this.subscribe(chatRoom)
      });

    //Subscribing 
    subscribe = (chatRoom) => {
      chatRoom.on('message', (payload) => {
          this.renderMessage(payload)
      });
    }
```
Now when a new chat is pushed in `this.myAllChats` , lets say 
```
this.myAllChats.push("ChannelD");
```
and hence again i call :
`this.createChat()`

now here comes issue when i now publish message to any of the channel
```
publishMessage = (chatObj, message) => {
     chatObj.emit('message', {
            text: message,
            channel: this.currentChat,
            date: new Date()
        });
}
```
This Text message will get published **multiple times on same Channel** because after creating "ChannelD" i accidently ran forLoop on Array of Channels which are already subscribed, and hence they all get **resubscribed** i.e new multiplex channels are created and hence causes Bandwidth and memory drain.

**Comment by ianjennings** [comment]
You're registering the listener multiple times. Calling ```.on()``` twice creates two callbacks. If you want to remove them, you need to use ```off```

**Comment by deepak1725** [comment]
Actually what we as developeres need to do is keeping a global array of already subscribed/registered listeners channels and hence maintaing its state. i.e like
```
  subscribe = (chatRoom) => {
        let isAlreadySubscribed = this.subscribedRooms.includes(chatRoom.channel);
        if (!isAlreadySubscribed) {
            this.subscribedRooms.push(chatRoom.channel);
            chatRoom.on('message', (payload) => {
                console.log("Payload", payload);
                this.renderMessage(payload)
            });
        }
    }
```
or your suggested Solution i.e running `.off()` each time before running forLoop.

What i need to know is: 
**Is this possible at your end to keep a check of channels having already registered listners not to re-register over and over again...??**
if not, then we need to follow either of above approaches..!!

**Comment by ianjennings** [comment]
This is just how event emitters work, If you register multiple listeners, you will get multiple callbacks. Your conditional approach is the correct one.
