### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by logan-jobzmall** [pubnub/chat-engine#316]
@ianjennings when will you guys be putting out new docs? P.S. all of the issues I was seeing seems to be resolved in 0.9.5 will be reporting any more bugs if I find anything.

**Comment by crgbaumgart** [comment]
Howdy @logan-jobzmall! You should expect to see new *updated* docs in the next couple days. Just wrapping up some minor edits in the meanwhile.

**Comment by crgbaumgart** [comment]
The documentation has been updated for the current ChatEngine v.0.9.5. Additionally @logan-jobzmall you may find this [new guide](https://www.pubnub.com/docs/chat-engine/troubleshooting-guide) on debugging helpful in the future. Happy coding 👍
