### ISSUE TITLE
PubNub ChatEngine “Converting circular structure to JSON” error after joining back to 1-1 chat using Angular

### ISSUE THREAD

**Issue by stephenlb** [pubnub/chat-engine#330]
> ⚠️ **Answer Requested:** ⚠️ https://stackoverflow.com/questions/49098089/pubnub-chatengine-converting-circular-structure-to-json-error-after-joining-ba

# Customer claims demo's use OLD ChatEnigne version.  Upgrading version in the demos seems to be the key to fixing.

I'm trying to wrap my head around this PubNub ChatEngine example using Angular for first time https://github.com/pubnub/chat-engine-examples/tree/master/angular/simple

In demo when you click on user from the list new channel with random name is generated and user invited to it. So if you leave chat click on user again you connect to new channel.

I'm trying to do 1-1 chat rooms, that you could leave than join back, so changed channel name to be clicked user uuid. Now if I leave the channel, join back to it and try to send message it's not being shown in list, though it's being sent and user you are chatting with receives it.

In console I'm getting "Uncaught (in promise) TypeError: Converting circular structure to JSON" when starting to type (as have chat engine typing indicator running) and after submit.

I guess that's something to do with removing chat from global scope using splice() method and after joining back new chat being added. It works in demo because there are getting new channel each time and removing it, but not if using same channel now. 
I tried to use splice() instead to see what happens. If I close chat and join back to it, it stays in DOM, and new one is added to scope, so have two same chat elements in DOM. If I type and send message on second one, it's not being displayed at it, but instead on first one that tried to close.
How could I get this working properly, can splice() be used in my case and I'm missing something else that is causing the error?

    $scope.leave = (index) => {
       $scope.chat.leave();
       $scope.chats.splice(index, 1);
       //$scope.chats.slice(index, 1);
       //$scope.chats.splice( $scope.chats.indexOf($scope.chat), 1 );
    }

    angular.module('chatApp', ['open-chat-framework'])
        .run(['$rootScope', 'ngChatEngine', function($rootScope, ngChatEngine) {

            $rootScope.ChatEngine = ChatEngineCore.create({
                publishKey: 'pub-c-d8599c43-cecf-42ba-a72f-aa3b24653c2b',
                subscribeKey: 'sub-c-6c6c021c-c4e2-11e7-9628-f616d8b03518'
            }, {
                debug: true,
                globalChannel: 'chat-engine-angular-simple'
            });

            // bind open chat framework angular plugin
            ngChatEngine.bind($rootScope.ChatEngine);

            // set a global array of chatrooms
            $rootScope.chats = [];

        }])
        .controller('Chat', function($scope) {

            $scope.chat.plugin(ChatEngineCore.plugin['chat-engine-typing-indicator']({
                timeout: 5000
            }));

            // every chat has a list of messages
            $scope.messages = [];

            // we store the id of the lastSender
            $scope.lastSender = null;

            // leave a chatroom and remove from global chat list
            $scope.leave = (index) => {
                $scope.chat.leave();
                $scope.chats.splice(index, 1);
            }

            // send a message using the messageDraft input
            $scope.sendMessage = () => {
                $scope.chat.emit('message', {
                    text: $scope.messageDraft
                });
                $scope.messageDraft = '';
            }

            // when we get notified of a user typing
            $scope.chat.on('$typingIndicator.startTyping', (event) => {
                event.sender.isTyping = true;
            });

            // when we get notified a user stops typing
            $scope.chat.on('$typingIndicator.stopTyping', (event) => {
                event.sender.isTyping = false;
            });

            // function to add a message to messages array
            let addMessage = (payload, isHistory) => {

                // if this message was from a history call
                payload.isHistory = isHistory;

                // if the last message was sent from the same user
                payload.sameUser = $scope.messages.length > 0 && payload.sender.uuid == $scope.messages[$scope.messages.length - 1].sender.uuid;

                // if this message was sent by this client
                payload.isSelf = payload.sender.uuid == $scope.me.uuid;

                // add the message to the array
                $scope.messages.push(payload);

            }

            // if this chat receives a message that's not from this sessions
            $scope.chat.search({
                event: 'message'
            }).on('message', function(payload) {

                // render it in the DOM with a special class
                addMessage(payload, true);
            })

            // when this chat gets a message
            $scope.chat.on('message', function(payload) {
                // render it in the DOM
                addMessage(payload, false);
            });

        })
        .controller('OnlineUser', function($scope) {

            // create a new chat
            $scope.newChat = function(user) {

                // define a channel
                let chan = user.uuid;

                // create a new chat with that channel
                let newChat = new $scope.ChatEngine.Chat(chan);

                // we need to auth ourselves before we can invite others
                newChat.on('$.connected', () => {

                    // this fires a private invite to the user
                    newChat.invite(user);

                    // add the chat to the list
                    $scope.chats.push(newChat);

                });

            };

        })
        .controller('ChatAppController', function($scope) {

            // create a user for myself and store as ```me```
            $scope.ChatEngine.connect(new Date().getTime(), {}, 'auth-key');

            $scope.ChatEngine.on('$.ready', (data) => {

                $scope.me = data.me;

                $scope.me.plugin(ChatEngineCore.plugin['chat-engine-random-username']($scope.ChatEngine.global));

                $scope.ChatEngine.global.plugin(ChatEngineCore.plugin['chat-engine-online-user-search']());

                // when I get a private invit
                $scope.me.direct.on('$.invite', (payload) => {

                    let chat = new $scope.ChatEngine.Chat(payload.data.channel);

                    chat.onAny((a,b) => {
                        console.log(a)
                    });

                    // create a new chat and render it in DOM
                    $scope.chats.push(chat);

                });

                // bind chat to updates
                $scope.chat = $scope.ChatEngine.global;

                // hide / show usernames based on input
                $scope.userSearch = {
                    input: '',
                    fire: () => {

                        // get a list of our matching users
                        let found = $scope.ChatEngine.global.onlineUserSearch.search($scope.userSearch.input);

                        // hide every user
                        for(let uuid in $scope.chat.users) {
                            $scope.chat.users[uuid].hideWhileSearch = true;
                        }

                        // show all found users
                        for(let i in found) {
                            $scope.chat.users[found[i].uuid].hideWhileSearch = false;
                        }

                    }
                };

                $scope.userAdd = {
                    input: '',
                    users: $scope.userAdd,
                    fire: () => {
                        if($scope.userAdd.input.length) {
                            $scope.userAdd.users = $scope.ChatEngine.global.onlineUserSearch.search($scope.userAdd.input);
                        } else {
                            $scope.userAdd.users = [];
                        }
                    }
                };

            });

        });

    <div class="container-fluid" ng-controller="ChatAppController">
          <div class="row">
            <div class="col-md-6">

                <div class="card">

                    <div class="card-block">
                        <h4 class="card-title">ChatEngine</h4>
                        <p class="card-text">Your are {{me.state.username}} with uuid {{me.uuid}}</p>
                    </div>

                    <ul id="online-list" class="list-group list-group-flush">

                      <li class="list-group-item" ng-repeat="(uuid, user) in chat.users" ng-hide="user.hideWhileSearch" ng-controller="OnlineUser">
                          <a href="#" ng-click="newChat(user)"> {{user.state.username}}</a>
                          <span class="show-typing" ng-show="user.isTyping">is typing...</span>
                      </li>

                    </ul>

                    <div class="card-block">

                        <form class="send-message" ng-submit="userSearch.fire()">
                            <div class="input-group">
                                <input id="usernameSearch" type="text" class="form-control message" placeholder="Search for Username" ng-change="userSearch.fire()" ng-model="userSearch.input">
                                <span class="input-group-btn">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </span>
                            </div>
                        </form>

                    </div>

                </div>

            </div>
            <div class="col-md-6">

              <div id="chats" class="row" ng-repeat="chat in chats" ng-controller="Chat">

                 <div class="chat col-xs-12">
                    <div class="card">

                        <div class="card-header">
                            <div class="col-sm-6">
                                {{chat.channel}}
                            </div>
                            <div class="col-sm-6 text-right">
                                <a href="#" ng-click="leave($index)" class="close">x</a>
                            </div>
                        </div>

                        <ul class="list-group list-group-flush online-list-sub">

                          <li class="list-group-item" ng-repeat="(uuid, user) in chat.users" ng-hide="user.hideWhileSearch" ng-controller="OnlineUser">
                            {{user.state.username}}
                            <span class="show-typing" ng-show="user.isTyping">is typing...</span>
                          </li>

                        </ul>

                        <div class="card-block">
                            <div class="log">
                                <div ng-repeat="message in messages" ng-class="{'hide-username': message.sameUser, 'text-muted': message.isHistory, 'text-xs-right': !message.isSelf}">
                                    <p class="text-muted username">{{message.sender.state.username}}</p>
                                    <p>{{message.data.text}}</p>
                                </div>
                            </div>
                            <p class="typing text-muted"></p>
                            <form class="send-message" ng-submit="sendMessage(chat)">
                                <div class="input-group">
                                    <input ng-model="messageDraft" ng-change="chat.typingIndicator.startTyping()" type="text" class="form-control message" placeholder="Your Message...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit">Send</button>
                                    </span>
                                </div>
                            </form>
                        </div>

                        <hr />

                        <div class="card-block">

                            <h6>Add a user to this chat</h6>

                            <fom ng-submit="userAdd.fire()">
                                <div class="input-group">
                                    <input id="usernameSearch" type="text" class="form-control message" placeholder="Add User" ng-change="userAdd.fire()" ng-model="userAdd.input">
                                </div>
                            </form>

                            <ul class="list-group list-group-flush online-list-sub">

                              <li class="list-group-item" ng-repeat="(uuid, user) in userAdd.users" ng-controller="OnlineUser">
                                  <a href="#" ng-click="invite(user, chat.channel)"> {{user.state.username}}</a>
                              </li>

                            </ul>

                        </div>

                    </div>
                </div>

              </div>

            </div>
          </div>
        </div>

**Comment by entracte** [comment]
Oh it's working correctly with chat-engine@0.9.5, I was using chat-engine@0.8.4, so can mark this as closed :)
