### ISSUE TITLE
Create React App build fails. Please publish pre-compiled.

### ISSUE THREAD

**Issue by bdlee** [pubnub/chat-engine#366]
When attempting a react production build:

```
Failed to minify the code from this file:

 	./node_modules/chat-engine/src/modules/emitter.js:11

Read more here: http://bit.ly/2tRViJ9
```

Compiling the code to ES5 before publishing will fix this problem for now

**Comment by ianjennings** [comment]
Hey @bdlee, try installing with the beta tag:

```npm install chat-engine@beta```

**Comment by junaid33** [comment]
Hello,

We tried integrating Chatengine into our react app but chat history does not work. When we downgraded the React version to 15.x, it worked. Will using chat-engine@beta fix this? Is there another solution we can use?

Thank you

**Comment by harsla** [comment]
Had a similar issue to @bdlee when attempting to build in angular-seed (error on emitter). Building chat-engine with the es2015 preset (es5) fixes the issue for projects that do not yet support newer ECMAScript versions. I have opened a pull request if this change ends up being useful to others:

PR: https://github.com/pubnub/chat-engine/pull/367

**Comment by ianjennings** [comment]
Thanks @harsla, that pull was merged. We just pushed 0.9.14 live, I'll release your changes as beta tomorrow.

**Comment by ianjennings** [comment]
@junaid33 do you get the same error as @bdlee? It sounds like you're having a problem with history specifically. Can you open a new issue?

**Comment by ianjennings** [comment]
I'd like to close this issue. Any updated anybody?
