### ISSUE TITLE
Chat Engine not works without react native Remote JS Debugging

### ISSUE THREAD

**Issue by rnavagamuwa** [pubnub/chat-engine#377]
I've created a chat application with chat engine and it works fine with Remote JS Debugging enabled.
But it doesn't work when I run the app without Remote JS Debugging.

### Steps to reproduce: 
Create a react native chat application(without expo) with "chat-engine":"0.9.14", "react": "16.2.0" and "react-native": "0.52.0".

### Solution
There seems to be a bug in the versions after chat-engine: 0.9.5. I managed to solve this by changing the chat-engine version to 0.9.5

**Comment by ianjennings** [comment]
This should be resolved in 0.9.18, can you update to that and reply here?

**Comment by rnavagamuwa** [comment]
I've updated to 0.9.18 and seems like it is working fine.
