### ISSUE TITLE
.emit not triggering .on events with new chats

### ISSUE THREAD

**Issue by killerham** [pubnub/chat-engine#384]
Only events emitting on global chat will trigger a `.on` event.

When turning on the debugger, there are no debug events triggered when calling emit unless I emit from the global chat.

**Comment by killerham** [comment]
After further testing, it appears that emit will only trigger a message on the same function that created the chat. But when calling emit on a timeout, the emit message will not trigger any events.

eg.

```
const chat = new ChatEngine.Chat('Michelle');

// will work
chat.emit("message", {text: "This message will trigger an event and will show up in search"});

setTimeout(()=>{
  // won't work
  chat.emit("message", {text: "This message will not trigger an event, but will show up in search"});
}, 3000)

```

**Comment by ianjennings** [comment]
This is likely a problem with your application scope and not ChatEngine itself. We use setTimeout within [our integration tests](https://github.com/pubnub/chat-engine/blob/master/test/integration/main.test.js#L572) exactly as described.
